### ISSUE TITLE
Unexpected character encountered while parsing value: �. Path '', line 0, position 0

### ISSUE THREAD

**Issue by weaz12** [Kevin0M16/NMSCoordinates#39]
This mod was working fine for me until I somehow managed to overwrite my current save (70+ hours) with a save that was a few years old (less than 1 hour). I ended up deleting the save from within NMS and ultimately downloaded a .DDS file from the Steam Sync Cloud website that allowed me to load up a previous game state. 

It was at this point that I started receiving the errors below when trying to use NMSCoordinates. Not sure this is relevant, but I immediately noticed the save files were now formatted differently. Originally, it was "save3.hg"  but is now "3, save3.hg". 

Other related issues:

If I select "backup current" it tells me to select a save slot despite already having one selected.
Error! 855 is also being displayed under the Coordinate Share section.
I am unable to select a Galaxy number in the fast travel section.

I have tried the following....however the problem persists:

Reinstalling NMSCoordinates
Deleting all files from the appdata/roaming/HelloGames folder
Deleting backup files from NMSCoordinate folder
Deleting JSON files from NMSCoordinates folder
Moving files with the Save File Manager section in NMSCoordinates
Toggling Travel Mode and Manual Travel on and off

I can try reinstalling NMS but before doing so I figured I'd look here for some guidance. I've attached the JSON error details txt file below. Please let me know if any additional information is needed. Thank you. 

![NMSCoordinates Error](https://user-images.githubusercontent.com/11304445/132061290-5f08ed79-66bb-414d-9b52-8f74d9ddd26c.PNG)

![image](https://user-images.githubusercontent.com/11304445/132063153-d6ea76ae-e346-4274-8c1a-7f492f415623.png)

![image](https://user-images.githubusercontent.com/11304445/132062773-fa6f6202-7554-439f-a075-3b784241c6b3.png)

![image](https://user-images.githubusercontent.com/11304445/132062910-3d99c15c-2183-431b-81cc-92dca3af4e79.png)

[JSON Error Details.txt](https://github.com/Kevin0M16/NMSCoordinates/files/7108341/JSON.Error.Details.txt)

**Comment by Kevin0M16** [comment]
Thanks for bringing up this issue. I apologize I didn't see this sooner. I haven't touched this since August 2020 when it was compatible with v2.62 (stated on the readme page). So if your game isn't v2.62 **AND** your save*.hg's were never touched by any other update, it's possible it could have negative effects on save files or possibly not work at all. Lot's of testing would be needed. I don't suggest using it at all at this point.

The very first zip file you created when opening NMSCoordinates should have your original save files in it. This might help to restore your save files.

If you or someone else is still passionate about fixing this for the latest update, let me know. I wasn't sure if this was still useful or needed after the changes in travel was made easier. To make this work, the save files (json) from v2.62 need to be compared to saves from v3.6. All the changes and additions noted and checked for compatibility.

**Comment by Kevin0M16** [comment]
Update: After investigating, the save files for the last update have changed format. So until I can add the new *decryption* method. This will not work. I'll see what I can find out.

**Comment by Kevin0M16** [comment]
Just an update. I know it's been a long while but I wanted to inform that I have worked on this and created the class to work with the new save files. Soon I will push a development branch if anyone is interested in testing it out.

This was my very first project and after looking it over again it's a real mess. I have plans to clean it up and possibly add new features if there are any suggestions post in issues.

Thanks.

Kevin0M16
